### ISSUE TITLE
auto restore?

### ISSUE THREAD

**Issue by edclement** [shiraji/HideToolWindowsEx#9]
I like the concept of hiding tool windows when typing begins. But is this plugin meant to automatically restore tool windows somehow? It would be nice if there was a shortcut key to restore tool windows or if the mouse is moved.

**Comment by shiraji** [comment]
HideToolWindowsEx provides `Hide/Restore` action. I assigned `hide all tool windows` key to this action in order to restore them.

![2016-11-13 8 44 39](https://cloud.githubusercontent.com/assets/3675458/20242746/79c466ba-a97d-11e6-859f-97649d9fd3dc.png)

**Comment by shiraji** [comment]
BTW, I won't be able to provide `auto-restore` since people want restore tool windows in variety of time.

**Comment by shiraji** [comment]
I will close this issue for now. If you have any question or idea, let me know.
